title: Sailaoda
subtitle: "明月不归沉碧海，白云愁色满苍梧"
description: "我知这世界，如露水版短暂，然而然而"
author: wuyesai
language: zh-CN
timezone: UTC

url: https://hexo.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: butterfly

highlight:
  enable: true
  line_number: false


disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: hexojs
github: sailaoda/sailaoda.github.io

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy: 
  type: 'git'
  repo: git@github.com/sailaoda/sailaoda.github.io.git
  branch: master